### ISSUE TITLE
Implement unpack and wildchars in dependencySet 

### ISSUE THREAD

**Issue by balbusm** [chrisdchristo/capsule-maven-plugin#41]
DependencySet has property unpack to determine if dependency should be unpacked or not. Could you implement this feature?
Please also implement wildchars for include tag, so multiple files can be added at once.
When include is not specified whole dependency should go into jar.
I think include should work on packed and unpacked file.
Reference https://maven.apache.org/plugins/maven-assembly-plugin/assembly.html#class_dependencySet

**Comment by chrischristo** [comment]
yeah can do that

**Comment by chrischristo** [comment]
See [v1.0.5](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-1.0.5) & [the readme](https://github.com/chrischristo/capsule-maven-plugin#filesets-and-dependencysets).

Essentially, you can now use now copy over the whole file (such as jar dependency) to the capsule - so you could use this to manipulate the built capsules to include your desired dependencies as requested in https://github.com/chrischristo/capsule-maven-plugin/issues/44.

There is also the unpack feature which at the moment currently only works with file types of ```jar```.

The wild chars implementation will come later.

**Comment by chrisdchristo** [comment]
Done the wildcard for `*`. Coming in 1.5.1.
