### ISSUE TITLE
Do not includes Repositories attribute by default

### ISSUE THREAD

**Issue by victornoel** [chrisdchristo/capsule-maven-plugin#51]
Hi, I couldn't add a new issue on the official repository so I try here instead :)

I noticed that with a very basic configuration of the plugin (without any specific caplet), there was a Manifest attributes Repositories added that contained my local settings.xml repositories settings.

```
Repositories: repo-snapshots(http://localhost:8081/nexus/content/groups/public-snapshots/) repo(http://localhost:8081/nexus/content/groups/public/)
```

I don't think it make sense to include that information, because:
- the maven caplet is not used
- it is local information that makes no sense to distribute

**Comment by chrisdchristo** [comment]
Hi @victornoel, yes be default, the plugin extracted the repo info from the pom. You can of course override this by including the desire ```Repositories``` manifest entry in the config:

```
<manifest>
  <entry>
    <key>Repositories</key>
    <value>central</value>
  </entry>
</manifest>
```

Is this sufficient for you? Or perhaps would you like a flag to exclude the ```Repositories``` entry completely?

**Comment by victornoel** [comment]
I'm not really bothered by it personally, but I think that by default, it is not correct to include this information. The best, IMHO, would be a flag to include the `Repositories` only if the user wants it.

**Comment by chrisdchristo** [comment]
Done - [1.4.2](https://github.com/chrisdchristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-1.4.2)

**Comment by victornoel** [comment]
Oh! Great reactivity :)
