### ISSUE TITLE
Allow capsule to be included by maven assembly

### ISSUE THREAD

**Issue by fzakaria** [chrisdchristo/capsule-maven-plugin#55]
I use a [maven docker plugin](https://fabric8io.github.io/docker-maven-plugin) that has the same setup as the maven-assembly-plugin.

Ultimately, I'd like to get my capsule JAR assembled into the docker image.

If I have an `assembly.xml` with
```

    <dependencySets>
        <dependencySet>
            <outputDirectory>${app.dir}/lib</outputDirectory>
            <useProjectArtifact>true</useProjectArtifact>
            <useTransitiveDependencies>true</useTransitiveDependencies>
            <unpack>false</unpack>
            <scope>runtime</scope>
        </dependencySet>
    </dependencySets>
```
The *capsule-jar* is not included

**Comment by chrisdchristo** [comment]
I'm not really familiar with the maven docker plugin or the maven assembly plugin. What is exactly you want the capsule plugin to implement?

**Comment by fzakaria** [comment]
I'm trying to figure out why its not registering itself as the `projectArtifact` and therefore included as a JAR.
The regular JAR and all dependencies are included but not the `-capsule.jar` one.
(This may be the wrong forum for this question)

**Comment by chrisdchristo** [comment]
Maybe this helps:

Have a look at this issued we resolved before: https://github.com/chrisdchristo/capsule-maven-plugin/issues/23

The plugin does attach the generated capsule as a maven artefact.

**Comment by chrisdchristo** [comment]
The classifier of the attached artifact is "capsule".
