### ISSUE TITLE
Make capsule name completely overridable

### ISSUE THREAD

**Issue by draenor** [chrisdchristo/capsule-maven-plugin#56]
**Type:** Feature request

**What:** 
To be able to configure the complete capsule name, not just the prefix defined by the customDescriptor `<finalName><customDescriptor>.jar`. 

**How:**
I suggest adding a `<finalName>` attribute that permit users of the plugin to specify the complete name,

**Why:**
We want to preserve the original artifact naming, e.g., `foo-1.7-SNAPSHOT-buildnum.jar` to upload to artifact server. We walso want to assemble the capsule separately as `foo.jar` to easily deploy and re-deploy it. 

**Rationale:**
The plugin creates a separate artifact next to the one default created during the `package` phase. As two separate artifacts they can have separate purpose and consequently the name is no longer guaranteed to be shared between the two.

**Comment by chrisdchristo** [comment]
This will be in the upcoming 1.5.0 release. But essentially we will have ```<fileName>``` and ```<fileDesc>``` to completely override the capsule jar's name - [see here](https://github.com/chrisdchristo/capsule-maven-plugin#custom-file-name).

```<fileName><fileDesc>.jar```

Note that the ```<customDescriptor>``` has been removed and replaced with ```<fileDesc>```.

**Comment by chrisdchristo** [comment]
Version 1.5.0 released.
