### ISSUE TITLE
Add capsule as pom dependency

### ISSUE THREAD

**Issue by pm47** [chrisdchristo/capsule-maven-plugin#58]
Hi,

Adding the capsule jar as dependency in the pom of the plugin would allow the maven dependency module to resolve it, which is particularly useful when doing `mvn dependency:go-offline` from projects that use `capsule-maven-module`. Nowadays a typical use-case for pre-fetching dependencies before compiling is when building docker images, because they get cached and the process becomes much more efficient. But even the normal use-case of being able to build the project offline is nice.

There must be a good reason why you don't do it that way, but I can't find it?

Cheers

**Comment by chrisdchristo** [comment]
The plugin has no Capsule dependency listed in its pom dependencies as it does not _depend_ on it directly. The plugin will use the property ```capsule.version``` (and the ```capsule.maven.version```) that you provide in your own project (or it will use the defaults) and resolve it at execution when building your capsule enabled jars. This allows you as the developer of your project to set whichever version of Capsule to use.

I didn't want to put any restriction on the Capsule version to users, as at the end of the day the built capsule-enabled jar will have actual Capsule code **embedded** inside. So with this in mind, I felt they needed the ability to easily define which capsule version they would like to use.

Perhaps adding Capsule as a dependency to your own project may resolve your issue?

**Comment by pm47** [comment]
> I didn't want to put any restriction on the Capsule version to users, as at the end of the day the built capsule-enabled jar will have actual Capsule code embedded inside. So with this in mind, I felt they needed the ability to easily define which capsule version they would like to use.

I see, that makes sense. Thanks!
